version: '3.9'

services:
  # hass - port 8213
  hass:
    image: homeassistant/home-assistant
    container_name: home-assistant
    volumes:
      - ./hass/config/:/config/
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - RPC_SECRET=${ARIA2_RPC_SECRET}
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ./aria2/config:/config
      - ./aria2/downloads:/downloads
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

  ariang:
    image: p3terx/ariang
    container_name: ariang
    command: --port 6880 --ipv6
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
    depends_on:
      - aria2

  alist:
    image: xhofe/alist:main
    container_name: alist
    restart: always
    volumes:
      - ./alist:/opt/alist/data
    ports:
      # infuse can not connect alist if use caddy reverse proxy
      - 5244:5244
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    depends_on:
      - aria2

  # portainer
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: --admin-password '${PORTAINER_ADMIN_PASSWD_HASHED}'
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-v:/data

  # caddy
  caddy:
    image: cstao/caddy
    build:
      context: caddy
      args:
        BUILD_VPN_PROXY: ${CADDY_BUILD_VPN_PROXY}
    container_name: caddy
    environment:
      ACME_AGREE: "true"
      TLS_EMAIL: ${CADDY_TLS_EMAIL}
      DOMAIN_ALIST: ${CADDY_DOMAIN_ALIST}
      DOMAIN_ARIANG: ${CADDY_DOMAIN_ARIANG}
      DOMAIN_ARIA2: ${CADDY_DOMAIN_ARIA2}
      DOMAIN_FILES: ${CADDY_DOMAIN_FILES}
      DOMAIN_PORTAINER: ${CADDY_DOMAIN_PORTAINER}
      ALIYUN_ACCESS_KEY_ID: ${CADDY_ALIYUN_ACCESS_KEY_ID}
      ALIYUN_ACCESS_KEY_SECRET: ${CADDY_ALIYUN_ACCESS_KEY_SECRET}
    restart: unless-stopped
    ports:
      - ${CADDY_PORT}:80
      - ${CADDY_SSL_PORT}:443
      - ${CADDY_SSL_PORT}:443/udp
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/caddyfile.d/:/etc/caddy/caddyfile.d/:ro
      - ./caddy/www/:/srv/:ro
      - ./caddy/.caddy:/root/.caddy
      - ./caddy/logs/:/var/logs/
      - caddy-data-v:/data
      - caddy-config-v:/config
    depends_on:
      - portainer
      - ariang
      - alist

volumes:
  portainer-v:
    name: portainer-data
  caddy-data-v:
    name: caddy-data
  caddy-config-v:
    name: caddy-config

networks:
  default:
    name: pi-services-network
