version: '3.9'

services:
  # hass - port 8213
  hass:
    image: homeassistant/home-assistant
    container_name: home-assistant
    volumes:
      - ./hass/config/:/config/
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

  # portainer
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: --admin-password '${PORTAINER_ADMIN_PASSWD_HASHED}'
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-v:/data
    networks:
      - portainer-network

  # cloud (2 service)
  cloud:
    image: arm32v7/nextcloud:latest
    container_name: cloud
    restart: always
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${CLOUD_DB_USERNAME}
      - MYSQL_PASSWORD=${CLOUD_DB_PASSWORD}
      - MYSQL_HOST=cloud-db
      - NEXTCLOUD_TRUSTED_DOMAINS=${CLOUD_DOMAIN}
      - NEXTCLOUD_ADMIN_USER=${CLOUD_ADMIN_USERNAME}
      - NEXTCLOUD_ADMIN_PASSWORD=${CLOUD_ADMIN_PASSWORD}
    depends_on:
      - cloud-db
    volumes:
      - cloud-data-v:/var/www/html
    networks:
      - cloud-network
  cloud-db:
    image: mariadb:10.6
    container_name: cloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - cloud-db-v:/var/lib/mysql
      - ./cloud/backup/:/var/lib/backup
    environment:
      - MYSQL_ROOT_PASSWORD==${CLOUD_DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${CLOUD_DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${CLOUD_DB_USERNAME}
    networks:
      - cloud-network

  # caddy
  caddy:
    image: cstao/caddy
    build:
      context: caddy
      args:
        BUILD_VPN_PROXY: ${CADDY_BUILD_VPN_PROXY}
    container_name: caddy
    environment:
      ACME_AGREE: "true"
      TLS_EMAIL: ${CADDY_TLS_EMAIL}
      DOMAIN_FILES: ${CADDY_DOMAIN_FILES}
      DOMAIN_PORTAINER: ${CADDY_DOMAIN_PORTAINER}
      DOMAIN_CLOUD: ${CADDY_DOMAIN_CLOUD}
      ALIYUN_ACCESS_KEY_ID: ${CADDY_ALIYUN_ACCESS_KEY_ID}
      ALIYUN_ACCESS_KEY_SECRET: ${CADDY_ALIYUN_ACCESS_KEY_SECRET}
    restart: unless-stopped
    ports:
      - ${CADDY_PORT}:80
      - ${CADDY_SSL_PORT}:443
      - ${CADDY_SSL_PORT}:443/udp
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/caddyfile.d/:/etc/caddy/caddyfile.d/:ro
      - ./caddy/www/:/srv/:ro
      - ./caddy/.caddy:/root/.caddy
      - ./caddy/logs/:/var/logs/
      - caddy-data-v:/data
      - caddy-config-v:/config
    depends_on:
      - portainer
      - cloud
    networks:
      - portainer-network
      - cloud-network

volumes:
  portainer-v:
    name: portainer-data
  cloud-data-v:
    name: cloud-data
  cloud-db-v:
    name: cloud-db
  caddy-data-v:
    name: caddy-data
  caddy-config-v:
    name: caddy-config

networks:
  default:
    name: pi-services-network
  portainer-network:
    name: portainer-network
  cloud-network:
    name: cloud-network
